[package]
name = "editor"
version.workspace = true
edition.workspace = true

[[bin]]
name = "longhorn-editor"
path = "src/main.rs"

[dependencies]
longhorn-core = { workspace = true }
longhorn-engine = { workspace = true }
longhorn-editor = { workspace = true }
eframe = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
